# Site settings
author: Raymond Willey
title: Information Overload
header-img: img/home-bg.png
email: raymond_willey@me.com
copyright_name: Raymond Willey
description: > # this means to ignore newlines until "baseurl:"
  Practical Approaches for Humans and Machines
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: rwilleyii
github_username:  rwilley83

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
